name: build and deploy to docker hub

on:
  push:
    branches:
      - main

jobs:
  base-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Dokcer Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.ubuntu
          push: true
          tags: firejox/omnetpp-dock:base

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  omnetpp-image:
    needs: base-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Dokcer Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: from=firejox/omnetpp-dock:base
          file: Dockerfile.omnetpp
          push: true
          tags: firejox/omnetpp-dock:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  xpra-image:
    needs: omnetpp-image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Dokcer Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: from=firejox/omnetpp-dock:latest
          file: Dockerfile.xpra
          push: true
          tags: firejox/omnetpp-dock:xpra

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
